# -*- coding: utf-8 -*-
"""Spoorthimpprg3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cciakP_oH9xqn0Xf3R6xMWDV6CJP_9JD
"""

import matplotlib.pyplot as plot
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

data=pd.read_csv('salary_data.csv')
data.head()
x=data.iloc[:,:-1]
y=data.iloc[:,1]
plot.scatter(x,y)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

reg=LinearRegression()
reg.fit(x_train,y_train)

y_pred=reg.predict(x_test)

y_pred

viz_train=plot
viz_train.scatter(x_train,y_train,color='red')
viz_train.title('Salary vs experience(training data)')
viz_train.xlabel('years of experience')
viz_train.ylabel('salary')

#predicting the salary of a person with 5 years of experience
print('The salary of a person with 5 years of experience:')
print(y_pred[5])